# Generated by Django 3.1 on 2021-01-07 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('category', models.CharField(default='origin', help_text='資料庫類別', max_length=64)),
                ('filename', models.CharField(help_text='錄音檔名', max_length=250)),
                ('fingerprinted', models.BooleanField(default=False, help_text='指紋識別狀態', null=True)),
                ('file_sha1', models.CharField(max_length=160)),
                ('total_hashes', models.IntegerField(default=0, help_text='指紋總數')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='建立時間')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='更新時間')),
            ],
        ),
        migrations.CreateModel(
            name='Fingerprint',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('hash', models.CharField(help_text='指紋加密', max_length=80)),
                ('offset', models.IntegerField(help_text='指紋起始點')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='建立時間')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='更新時間')),
                ('recording', models.ForeignKey(help_text='音檔id', on_delete=django.db.models.deletion.CASCADE, related_name='recording', to='main.recording')),
            ],
            options={
                'unique_together': {('recording', 'hash', 'offset')},
            },
        ),
    ]
