# Generated by Django 3.1 on 2020-12-01 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_fingerprintwithnoisereduction_recordingwithnoisereduction'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FingerprintWithNoiseReduction',
            new_name='FingerprintWithNR',
        ),
        migrations.RenameModel(
            old_name='RecordingWithNoiseReduction',
            new_name='RecordingWithNR',
        ),
    ]
