# Generated by Django 3.1 on 2021-06-04 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201201_1059'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FingerprintWithNR',
        ),
        migrations.DeleteModel(
            name='RecordingWithNR',
        ),
    ]
